### ISSUE TITLE
Checkout gammasim-tools?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#1]
Why not checkout gammasim-tools and build it as well? At the moment, after building the docker, we cannot run anything.

**Comment by GernotMaier** [comment]
Someone told me that it is better to have gammasims in an accessible directory

```
$(pwd)/gammasim-tools:/gammasim-tools
```

But we should discuss what kind of containers we want:
- for running gamma-sims —> then we should do the checkout in the container
- for developing code —> outside, so that you can use your favorite IDE?

**Comment by orelgueta** [comment]
But can't you create the directory so that it is accessible, and then clone the repo to it?
I will run a test to make sure it works, but if it does, I think this answers both your options.

**Comment by GernotMaier** [comment]
Yes, but I thought of an application where you run several containers in parallel, but accessing the same gammasim-tools directory (e..g, if you develop and try to do several checks in parallel)

**Comment by orelgueta** [comment]
Oh, I don't know what would be the use case for this, but we can keep it in mind. For now I suggest we make the container "usable out of the box".

**Comment by orelgueta** [comment]
After playing for a while, I retract my original suggestion. Later we can install gammasim-tools in the workdir, but while we are developing, it's better this way.
However, I do suggest that we delete the .gitignore from the gammasim-tools directory, so that we can git clone directly to it (can't if it's not empty). I can do it if you approve.

**Comment by GernotMaier** [comment]
Approve

**Comment by orelgueta** [comment]
Git can't track an empty directory........
Fine, will live with it as is, closing.
