### ISSUE TITLE
Change to use new setup functionality?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#12]
https://github.com/gammasim/containers/blob/97fa5aba87eeb5002f8e69fd258dc10a08c901a5/dev/Dockerfile#L49

@GernotMaier, is it worth changing also here to use the new setup functionality?

**Comment by GernotMaier** [comment]
This is unfortunately not possible for the dev container: not that while building the Dockerfile, no gammasim-tools installation exists. 

I've tried to add the `pip install` command to be executed when starting up the container, but couldn't get it run (I am still struggling with the ENTRYPOINT and CMD functionalities). This means that each time you start up the container at this point, you first have to run the `pip install` command. This is not a good solution, but I don't have a better idea.

For the prod container, which includes a full gammasim-tools installation (master branch), this has been added (see PR #16)

**Comment by orelgueta** [comment]
Yes I definitely meant the prod container and not the dev one. For the dev one find an entry point solution would be very good. I am therefore inclined to leave this issue open to remind us to dig further in the next few weeks.

**Comment by GernotMaier** [comment]
I think this has been addressed with PR #16 and we can close this issue.

**Comment by orelgueta** [comment]
Well, I left it open in order to remember to try to find a solution for the dev container like the entry point solution you mentioned. However, I agree the original issue is resolved.

**Comment by GernotMaier** [comment]
Please open a new issue for that, I am otherwise confused!
