### ISSUE TITLE
Run pip install when starting the dev container

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#17]
At the moment we need to run `pip install .` every time we open the dev container in order to add the package to the path. There might/should be a way to do it automatically using the ENTRYPOINT and CMD options of Docker. We should investigate and see if it's possible.

**Comment by GernotMaier** [comment]
Had a look into this:

`ENTRYPOINT` is executed by docker before the mount bind, meaning it is not possible to use this functionality.

As a solution, use this command:
```
docker run --rm -it -v "$(pwd)/external:/workdir/external" gammasim-tools-dev-test bash -c "$(cat ./entrypoint.sh) && bash"
```

This executes the `entrypoint.sh` script, which runs the `pip install` command (and also sources a `set_DB_environ.sh` script to set the database user names and passwords while starting the image.

**Comment by orelgueta** [comment]
OK! I guess this is the best we can do. I am closing this issue then.
