### ISSUE TITLE
DB connection

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#2]
The docker does not use the kerberos token of the host machine (understandable). That means we cannot connect to the DB from within the docker, which makes the container fairly useless...
Unclear how to solve this issue. Requires a discussion.

**Comment by GernotMaier** [comment]
There seems to be a solution around, google delivers e.g.

https://docs.centrify.com/Content/inst-depl/CoreOSServicesCentOSKerberos.htm

For singularity container, there is a description on the DESY confluence:
https://confluence.desy.de/display/IS/Using+Kerberos+Tickets+and+AFS+Tokens+from+Inside+a+Container

We should try this (I can’t do this, until I have a laptop again).

**Comment by orelgueta** [comment]
> There seems to be a solution around, google delivers e.g.
> 
> https://docs.centrify.com/Content/inst-depl/CoreOSServicesCentOSKerberos.htm

Yeah, I found it as well, but I thought it might require a discussion, considering we are dealing with DESY security.

**Comment by orelgueta** [comment]
New suggestion:
A user creates a token as usual and binds the token file to the docker via 

`docker run --rm -it -v "$(pwd)/gammasim-tools:/gammasim-tools" -v "/tmp/token.krb:/tmp/token.krb" gammasim-tools-dev bash`

Together with a few additions to the Dockerfile (see #5 ), the user can connect directly to the DB (an updated dbDetails.yml is necessary).
