### ISSUE TITLE
sim_telarray location

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#3]
We should add the default container location of sim_telarray to simtelPath in gammasim-tools. That is, we should always search for sim_telarray in "/workdir/sim_telarray", on top of the simtelPath.

* This issue technically is for gammasim-tools, but I open it here because until we make the container useful, this issue is not relevant for gammasim-tools. Don't want to create noise there.

**Comment by orelgueta** [comment]
Related to this, we should change the location of sim_telarray to be "/workdir/sim_telarray". Currently it is extracted directly in "workdir".
This is done in a308235.

**Comment by GernotMaier** [comment]
@orelgueta : Looking at your first point above: not entirely clear what you mean with that. We set 

ENV SIMTELPATH="/workdir/sim_telarray/"

in the Dockerfile, what else is needed?

**Comment by orelgueta** [comment]
Hard to remember, it's been almost a year...

If I am not mistaken, this issue is not really for the container repository, it is for gammasim-tools. As I mentioned originally, I opened it here because I did not want to add anything related to containers to gammasim-tools until we actually use it.

Now the actual issue:
In gammasim-tools we have in the config file a simtel_array path (https://github.com/gammasim/gammasim-tools/blob/7198a17f59c81eaa92a7f287ade04b321530abd9/config_template.yml#L33). We should put there in the template "/workdir/sim_telarray/" and any user can add their own if they have it. That way, all of our containers will work out of the box and users can ignore it and add their own. @RaulRPrado do you see an issue of adding it already?

**Comment by GernotMaier** [comment]
Really not the most important issue, but the solution is to put custom config.yml file into ./external (see https://github.com/gammasim/containers/blob/main/dev/external/config.yml). Here SIMTELPATH is set correctly, and one does not have to set anything when starting the container (conda environment is set, SIMTELPATH, PYTHONPATH also).

Is that a reasonable solution?

**Comment by orelgueta** [comment]
Yes, this is what I did today indeed, it's a good enough solution.

Either way, since this issue has a comment once a year on average, it's probably not a very important one and can be closed =)
