### ISSUE TITLE
Remove bc from the software installed in the container?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#31]
sim_telarray's `generic.sh` requires `bc` for doing some basic math operations before launching simulations. They are relevant for CTA only in 3 places, checking the CORSIKA cone and calculating the zenith angle (zenith angle + offset). The `bc` tool is very small, so installing it as well is not costly. However, we might want to remove even these basic calculations from sim_telarray and putting them in the gammasim_tools scripts (at least that's the plan). 
For now, while I am still developing the scripts, I installed `bc` on my local version. I therefore opened this issue in order to discuss what we should do and also not forget to add `bc` to the dependencies if we decide to decide later.

**Comment by GernotMaier** [comment]
I am fine with adding it to the containers for now and replacing with time these script in sim_telarray. bc is actually a quite nice tool.

**Comment by GernotMaier** [comment]
@orelgueta - this can be closed? I see that `bc` has been added.

**Comment by orelgueta** [comment]
I kept it open in order to remind myself to remove it actually once I know for a fact we don't need it. I will edit the title.

**Comment by GernotMaier** [comment]
Replaced by https://github.com/gammasim/simtools/issues/539
