### ISSUE TITLE
Install latex

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#4]
We use latex in our plots, so we need to install latex in the docker.

**Comment by GernotMaier** [comment]
Wouldn’t it be most consistent to add this to the environment.yml file?

**Comment by orelgueta** [comment]
Yeah, maybe, I didn't think about it. It might create quite large duplication for non-container use though. (Since we all have latex installed system-wide, we don't need to install it also within conda.)
I will run a couple of tests, but in the meantime I added the latex installation to the Docker.

**Comment by GernotMaier** [comment]
Again, we can have several different docker definitions, with different goals (e.g., does the average user need latex?): using gammasim-tools, developer, ...

And we shouldn’t do a full tex installation with several GBs, but something smaller. e.g. https://tex.stackexchange.com/questions/397174/minimal-texlive-installation

**Comment by orelgueta** [comment]
Yes, I have a few examples from my linux days of minimal tex installations I was going to try. Either way it is definitely not several GB, that happens only with apple...

The docker definitions are OK, but both users and developers will needs latex. The only possible user that might not need it is a batch user that is used by DIRAC in production.

**Comment by GernotMaier** [comment]
Ok - we can define later a docker image for batch usage.

Even the current image can be made smaller (e.g., by deleting everything you need for the compilation, but not for the execution)

**Comment by orelgueta** [comment]
After a few tests, it looks like my original solution is the easiest/smallest. The minimal installation directly from tug.org is smaller to begin with, but is much more involved and ends up being only ~50-100 MB smaller than the yum install (the whole tex installation is 250 MB).
Installing via conda provides less control, ends up being bigger and I am not sure it is better putting the latex dependency within conda.

**Comment by GernotMaier** [comment]
This is fine with me, as this Docker container is for development.

We should work on optimising the size when we prepare a production container.

(And I will not really test this until I have a new laptop)

**Comment by orelgueta** [comment]
OK, so since this works now and is an accepted solution, I am closing this issue.
