### ISSUE TITLE
Get sim_telarray from GitLab?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#6]
Konrad created a mirror of sim_telarray on GitLab (https://gitlab.cta-observatory.org/Konrad.Bernloehr/sim_telarray/-/tree/master), so perhaps we can get it from there during the building process.
The location will probably move soon to be under DPPS, so we should wait a few weeks before making the change.

**Comment by GernotMaier** [comment]
Sounds good (can’t access the gitlab right now)

**Comment by GernotMaier** [comment]
Do I see it correctly that this works only for sim_telarray, but not for CORSIKA? So we would need to get access also to the CORSIKA git?

**Comment by orelgueta** [comment]
Yes. Understandable that it's not included in the sim_telarray gitlab of course, but it means we need to look into it a bit. 
Need to see what's the most efficient way to get both packages and whether Konrad's modification to CORSIKA work out of the box if we do get them separately.

**Comment by GernotMaier** [comment]
Does Konrad modify CORSIKA? I thought it is only about setting the correct compile parameters.

**Comment by orelgueta** [comment]
I meant the IACT/ATMO package (https://gitlab.cta-observatory.org/Konrad.Bernloehr/sim_telarray/-/tree/master/corsika). I don't know if it's included also in "vanilla" CORSIKA or is it added only in Konrad's tar package.

**Comment by GernotMaier** [comment]
Yes, this is included in CORSIKA as bernlohr.tar.gz Needed for all Cherenkov analysis (also non-imaging).

**Comment by orelgueta** [comment]
OK!
So I guess it would just be a simple test of getting the two packages and running Konrad's build_all as a test (probably slightly modified).

**Comment by GernotMaier** [comment]
To follow this up (after almost one year): this gitlab version doesn't provide tags or releases, so I would rather download the tar package either from MPIK or put the tar  package in cloud directory.

**Comment by orelgueta** [comment]
Yes, in the meantime we also learned that the GitLab version is not always up to date. I suggest we close this and return to this question in the future.
